### PR TITLE
Add round-to function

### PR DESCRIPTION
**Pull request by benhinchley**
I added a roundTo function to the numeric functions. I often find myself working with numbers that I want rounded to a certain number of decimal places, and in the past have built this functaionality with a large sass function.

### CODE REVIEW

**Comment by eoneill** [comment]
I would suggest simplifying the implementation to...

``` scss
@function to-fixed($number, $n: 0) {
  $n: math-pow(10, $n);
  @return round($number * $n) / $n;
}
```

This will correctly preserve units for you (e.g. `to-fixed(5.4321px, 2) // -> 5.43px`) and doesn't need an extra javascript function.

**Comment by benhinchley** [comment]
@eoneill fair point, will make those changes

**Comment by eoneill** [comment]
Thanks for making all the updates!

**Comment by benhinchley** [comment]
@eoneill All good :smile:  :+1:

**Pull request merged**
